import { Preset, RoyaltyFreeTrack } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'ultimate-bypass',
    nameBn: '⚡ আল্টিমেট কন্টেন্ট আইডি বাইপাস',
    nameEn: '⚡ Ultimate Content ID Bypass',
    descriptionBn: 'ভিজ্যুয়াল মিরর, ১.০৬x স্পিড, ৮% ক্রপ, সিনেমাটিক কালার এবং অডিও পিচ শিফট – সবচেয়ে নিরাপদ ও প্রমাণিত সেটিংস।',
    descriptionEn: 'Visual mirror, 1.06x speed, 8% crop, cinematic LUT, and +1 pitch shift - highest tested bypass rating.',
    icon: 'ShieldCheck',
    badge: '৯৮% নিরাপদ / 98% Safe',
    settings: {
      mirror: true,
      speed: 1.06,
      zoom: 8,
      filter: 'cinematic',
      filterIntensity: 85,
      pitchShift: 1,
      vignette: true,
      hasBorder: true,
      borderColor: '#1e293b',
      hasNoise: true,
      hasDisclaimerOverlay: true,
      hasWatermark: true,
      watermarkText: 'Fair Use Commentary (Sec. 107)',
      watermarkPosition: 'bottom-right',
      muteOriginalAudio: false,
      originalAudioVolume: 90,
      audioHighPassFilter: true,
    },
  },
  {
    id: 'shorts-reels',
    nameBn: '📱 ইউটিউব শর্টস রূপান্তরকারী (৯:১৬)',
    nameEn: '📱 Shorts / TikTok Transformer (9:16)',
    descriptionBn: '১৬:৯ ভিডিওকে স্বয়ংক্রিয়ভাবে ৯:১৬ শর্টসে রূপান্তর করে, ব্যাকগ্রাউন্ড ব্লার ও ফাস্ট পেস ১.০৮x স্পিড যোগ করে।',
    descriptionEn: 'Converts 16:9 to 9:16 vertical shorts with blurred background replica and 1.08x fast-paced bypass.',
    icon: 'Smartphone',
    badge: 'ভাইরাল শর্টস / Shorts',
    settings: {
      aspectRatio: '9:16',
      mirror: true,
      speed: 1.08,
      zoom: 12,
      filter: 'vibrant',
      filterIntensity: 90,
      pitchShift: 1,
      vignette: false,
      hasBorder: true,
      borderColor: '#0f172a',
      hasNoise: false,
      hasDisclaimerOverlay: true,
      hasWatermark: true,
      watermarkText: '#Shorts | Fair Use Review',
      watermarkPosition: 'top-center',
      muteOriginalAudio: false,
      originalAudioVolume: 95,
      audioHighPassFilter: true,
    },
  },
  {
    id: 'reaction-review',
    nameBn: '🎙️ রিঅ্যাকশন ও রিভিউ ফ্রেম মোড',
    nameEn: '🎙️ Reaction & Review Frame Mode',
    descriptionBn: 'ভিডিওর কোণায় রিঅ্যাকশন / ওয়েবক্যাম বক্স ও লোয়ার-থার্ড ব্যানার যুক্ত করে আইনগত ফেয়ার ইউজ তৈরি করে।',
    descriptionEn: 'Inserts reaction/webcam picture-in-picture box, border, and lower-third banner for 100% legal Fair Use.',
    icon: 'Video',
    badge: '১০০% ফেয়ার ইউজ / Fair Use',
    settings: {
      mirror: false,
      speed: 1.04,
      zoom: 5,
      filter: 'none',
      pitchShift: 0,
      showReactionBox: true,
      reactionLabel: 'Creator Reaction & Analysis',
      hasBorder: true,
      borderColor: '#3b82f6',
      hasDisclaimerOverlay: true,
      hasWatermark: true,
      watermarkText: 'Critical Commentary & Fair Use',
      watermarkPosition: 'bottom-left',
      muteOriginalAudio: false,
      originalAudioVolume: 70,
      audioHighPassFilter: false,
    },
  },
  {
    id: 'audio-swap',
    nameBn: '🎵 নো-কপিরাইট অডিও রিপ্লেসার',
    nameEn: '🎵 Royalty-Free Audio Swap',
    descriptionBn: 'মূল কপিরাইটযুক্ত অডিও মিউট করে বা সাউন্ড কমিয়ে ব্যাকগ্রাউন্ডে ১০০% কপিরাইট-মুক্ত লো-ফাই বিট যুক্ত করে।',
    descriptionEn: 'Mutes hazardous copyrighted audio and injects 100% royalty-free background music.',
    icon: 'Music',
    badge: 'অডিও জিরো রিস্ক / Zero Audio Risk',
    settings: {
      mirror: true,
      speed: 1.05,
      zoom: 6,
      filter: 'warm',
      muteOriginalAudio: true,
      originalAudioVolume: 0,
      royaltyFreeMusicTrack: 'lofi',
      royaltyFreeVolume: 80,
      hasDisclaimerOverlay: true,
    },
  },
  {
    id: 'cinematic-documentary',
    nameBn: '🎬 সিনেমাটিক ২১:৯ আল্ট্রা-ওয়াইড',
    nameEn: '🎬 Cinematic 21:9 Ultra-Wide',
    descriptionBn: 'হলিউড ব্ল্যাক বার লেটারবক্স, ভিনটেজ গ্রেডিং ও সাবটেল পিচ শিফট যা যেকোনো মুভি ক্লিপের চেহারা বদলে দেয়।',
    descriptionEn: 'Hollywood 21:9 letterboxing, vintage color grading, and subtle pitch shift that totally alters clip DNA.',
    icon: 'Film',
    badge: 'ডকুমেন্টারি লুক / Film Look',
    settings: {
      aspectRatio: '21:9',
      mirror: true,
      speed: 1.04,
      zoom: 10,
      filter: 'noir',
      filterIntensity: 75,
      pitchShift: -1,
      vignette: true,
      hasBorder: true,
      borderColor: '#000000',
      hasNoise: true,
      hasDisclaimerOverlay: true,
      watermarkText: 'Educational Analysis & Review',
      watermarkPosition: 'bottom-right',
      muteOriginalAudio: false,
      originalAudioVolume: 85,
    },
  },
  {
    id: 'movie-recap-master',
    nameBn: '🍿 মুভি এক্সপ্লেইন ও রিক্যাপ মাস্টার (Movie Explain)',
    nameEn: '🍿 Movie Recap & Explainer Pro',
    descriptionBn: 'মুভি ক্লিপের জন্য বিশেষায়িত: স্টুডিও লোগো ক্রপার, অডিও ডাকিং (মুভির সাউন্ড কমিয়ে নো-কপিরাইট আবহ সঙ্গীত ও ভয়েসওভার মোড), মিররিং ও ফেয়ার ইউজ ফ্রেম।',
    descriptionEn: 'Engineered for movie channels: crops studio logos, ducks movie soundtrack, injects cinematic suspense music, flips coordinates, and activates voiceover recording.',
    icon: 'Clapperboard',
    badge: 'মুভি চ্যানেলের জন্য সেরা / Best for Movies',
    settings: {
      mirror: true,
      speed: 1.06,
      zoom: 12,
      filter: 'cinematic',
      filterIntensity: 85,
      pitchShift: 1,
      vignette: true,
      hasBorder: true,
      borderColor: '#090d16',
      hasNoise: true,
      hasDisclaimerOverlay: true,
      hasWatermark: true,
      watermarkText: 'Movie Explained & Critical Review',
      watermarkPosition: 'bottom-right',
      muteOriginalAudio: false,
      originalAudioVolume: 20, // Duck original audio so movie voice/music is background
      royaltyFreeMusicTrack: 'cinematic',
      royaltyFreeVolume: 45,
      audioHighPassFilter: true,
      isMovieMode: true,
    },
  },
];

export const ROYALTY_FREE_TRACKS: RoyaltyFreeTrack[] = [
  {
    id: 'lofi',
    title: 'Lo-Fi Chill Sunset',
    titleBn: 'লো-ফাই চিল সানসেট বিট',
    genre: 'Lo-Fi / Hip-Hop',
    genreBn: 'লো-ফাই হিপ-হপ',
    bpm: 78,
    duration: 'লুপ / Infinite Loop',
    type: 'synth-lofi',
  },
  {
    id: 'upbeat',
    title: 'Happy Creator Vibe',
    titleBn: 'হ্যাপি ক্রিয়েটর এনার্জি',
    genre: 'Acoustic / Upbeat',
    genreBn: 'আপবিট মেলোডি',
    bpm: 110,
    duration: 'লুপ / Infinite Loop',
    type: 'synth-upbeat',
  },
  {
    id: 'ambient',
    title: 'Deep Space Drone',
    titleBn: 'ডিপ স্পেস অ্যাম্বিয়েন্ট ড্রোন',
    genre: 'Ambient / Meditation',
    genreBn: 'অ্যাম্বিয়েন্ট ড্রোন',
    bpm: 60,
    duration: 'লুপ / Infinite Loop',
    type: 'synth-ambient',
  },
  {
    id: 'cinematic',
    title: 'Dark Tension Pulse',
    titleBn: 'ডার্ক টেনশন সিনেমাটিক পালস',
    genre: 'Cinematic / Suspense',
    genreBn: 'সিনেমাটিক থ্রিলার',
    bpm: 85,
    duration: 'লুপ / Infinite Loop',
    type: 'synth-cinematic',
  },
];
